# Generated by Django 4.0.4 on 2022-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('suggested', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('seller', models.CharField(default='Unknown', max_length=200)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
