# Generated by Django 4.0.4 on 2022-05-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0002_order_buyer_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.order')),
            ],
        ),
    ]
