# Generated by Django 4.0.4 on 2022-05-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0005_order_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='order_number',
            new_name='order',
        ),
    ]
