# Generated by Django 4.0.4 on 2022-05-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0006_rename_order_number_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
